# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/OneDrive - USTC/WorkPlace/2022spring/COD_Lab/Lab5/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/dist_data_ram/dist_data_ram.xci
# IP: The module: 'dist_data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive - USTC/WorkPlace/2022spring/COD_Lab/Lab5/pipeline_cpu/pipeline_cpu.gen/sources_1/ip/dist_data_ram/dist_data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_data_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/OneDrive - USTC/WorkPlace/2022spring/COD_Lab/Lab5/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/dist_data_ram/dist_data_ram.xci
# IP: The module: 'dist_data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive - USTC/WorkPlace/2022spring/COD_Lab/Lab5/pipeline_cpu/pipeline_cpu.gen/sources_1/ip/dist_data_ram/dist_data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
