# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/OneDrive - USTC/2022spring/COD/Lab/Lab4/CPU/CPU.srcs/sources_1/ip/dist_ins_mem/dist_ins_mem.xci
# IP: The module: 'dist_ins_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive - USTC/2022spring/COD/Lab/Lab4/CPU/CPU.gen/sources_1/ip/dist_ins_mem/dist_ins_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_ins_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/OneDrive - USTC/2022spring/COD/Lab/Lab4/CPU/CPU.srcs/sources_1/ip/dist_ins_mem/dist_ins_mem.xci
# IP: The module: 'dist_ins_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive - USTC/2022spring/COD/Lab/Lab4/CPU/CPU.gen/sources_1/ip/dist_ins_mem/dist_ins_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_ins_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
